### ISSUE TITLE
Bulldozer should only merge PRs into the default branch

### ISSUE THREAD

**Issue by pkoenig10** [palantir/bulldozer#92] opened 2019-02-13 01:26 UTC
If a PR is created whose base branch has no branch protection rules, then bulldozer will immediately merge that PR.

This seems undesirable. Opening a PR with a non-default base branch is a common workflow when one PR depends on another currently open PR.

**Comment by sixinli** [comment] 2019-02-13 17:35
👍  its kind of bad when we are PRing another PR

**Comment by bluekeyes** [comment] 2019-02-13 18:47
What kind of whitelist/blacklist configuration are you using here? It sounds like this is only a problem if you have a blacklist-only configuration (i.e. everything merges by default.)

Would something like #86 solve this problem? I don't want to force Bulldozer to only operate on the default branch, as that eliminates workflows like using it to merge into both `master` and `develop` (like in #89.)

**Comment by pkoenig10** [comment] 2019-02-13 19:35
Yes #86 seems like a better, more general solution to this problem. Feel free to close this.

**Comment by bluekeyes** [comment] 2019-02-14 01:31
Sounds good, closing as a duplicate of #86.

**Closed as completed by bluekeyes** 2019-02-14 01:31 UTC
Labels: duplicate
