### ISSUE TITLE
[Question] Is update possible for PR from forked repository ?

### ISSUE THREAD

**Issue by tanvn** [palantir/bulldozer#120] opened 2019-06-05 04:45 UTC
Hi,
I have a question, that today I am trying to add the "update-me" label to one of my Pull request.
But then I got the log 
```
    "message": "Pull request is from a fork, cannot keep it up to date with base ref"
```

my question is, is it possible to let bulldozer update my PR when it's from a fork ?

Thank you guys for your amazing product !

**Comment by asvoboda** [comment] 2019-06-05 08:55
Hey @tanvn ,

I'm closing because I think this is a duplicate of https://github.com/palantir/bulldozer/issues/66

**Closed as completed by asvoboda** 2019-06-05 08:55 UTC
Labels: duplicate
